version: '3.0'

services:
  mysql:
    image: mysql:8.3.0
    container_name: "${DATE_TIME}_mysql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER_FILE=/run/secrets/db_user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
    volumes:
      - /storage/mysql/go:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
    secrets:
      - db_user
      - db_password
      - db_root_password

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
